DROP DATABASE IF EXISTS test;

CREATE DATABASE test DEFAULT CHARACTER SET 'utf8' collate utf8_general_ci;

USE test;

create table User
(
	id int(8) NOT NULL PRIMARY KEY auto_increment,
	name varchar(25),
	age int,
	isAdmin bit,
	dateCreated timestamp default current_timestamp
);

INSERT INTO user(name, isAdmin, age)
VALUES ("Black Paules", true, 22),
("Claud Dublin", true, 33),
("John Jenkins", true, 33),
("Colonel Blackberry", true, 28),
("Seagate Paules", false, 27),
("Mishele Stonemight", false, 38),
("Mishele Stonemight", false, 27),
("Bowie Molly", false, 35),
("Bowie Paules", false, 39),
("Colonel Layers", false, 19),
("Seagate Jenkins", false, 26),
("Mishele Banshee", false, 44),
("Bright Stonemight", false, 44),
("King Stonemight", false, 47),
("Bowie Layers", false, 37),
("Claud Grey", false, 36),
("Colonel Strite", false, 41),
("John Banshee", false, 44),
("Black Blackberry", false, 31),
("Black Strite", false, 25),
("Claud Paules", false, 24),
("Black Banshee", false, 21),
("Bright Dublin", false, 21),
("Bright Layers", false, 46),
("King Dublin", false, 36),
("Colonel Grey", false, 37),
("Bowie Stonemight", false, 38),
("Black Grey", false, 41),
("Mishele Stonemight", false, 35),
("Bowie Stonemight", false, 27),
("Seagate Strite", false, 42),
("John Banshee", false, 46),
("Mishele Grey", false, 24),
("Bowie Molly", false, 38),
("Colonel Paules", false, 41),
("Leeroy Molly", false, 25),
("Seagate Strite", false, 27),
("Bright Blackberry", false, 46),
("Colonel Banshee", false, 19),
("Claud Strite", false, 28),
("Bowie Banshee", false, 40),
("Claud Dublin", false, 43),
("Black Paules", false, 45),
("Bowie Jenkins", false, 40),
("Colonel Paules", false, 38),
("Bright Molly", false, 23),
("Bowie Stonemight", false, 46),
("John Blackberry", false, 27),
("Mishele Stonemight", false, 47),
("Black Banshee", false, 43),
("Claud Jenkins", false, 24),
("John Paules", false, 40),
("Bright Strite", false, 31),
("Seagate Layers", false, 18),
("Bright Strite", false, 28),
("Mishele Paules", false, 32),
("Claud Grey", false, 24),
("Leeroy Layers", false, 20),
("Mishele Strite", false, 18),
("Seagate Grey", false, 23),
("Seagate Strite", false, 41),
("King Jenkins", false, 33),
("Claud Dublin", false, 37),
("Black Molly", false, 21),
("Black Stonemight", false, 44),
("Claud Jenkins", false, 47),
("Seagate Dublin", false, 29),
("John Strite", false, 46),
("Bright Stonemight", false, 36),
("Claud Molly", false, 25),
("King Molly", false, 34),
("Colonel Stonemight", false, 39),
("Black Strite", false, 29),
("Colonel Banshee", false, 47),
("Bright Paules", false, 40),
("King Stonemight", false, 30),
("Bowie Dublin", false, 42),
("Mishele Layers", false, 31),
("Black Strite", false, 26),
("Seagate Molly", false, 31),
("Colonel Banshee", false, 35),
("John Strite", false, 47),
("Bowie Blackberry", false, 25),
("Leeroy Strite", false, 23),
("King Blackberry", false, 18),
("Mishele Paules", false, 45),
("Claud Banshee", false, 30),
("Bowie Strite", false, 21),
("Bright Paules", false, 20),
("Leeroy Paules", false, 39),
("Colonel Dublin", false, 41),
("Black Blackberry", false, 26),
("King Strite", false, 23),
("Bright Strite", false, 43),
("King Banshee", false, 20),
("King Stonemight", false, 36),
("Colonel Molly", false, 20),
("Bowie Strite", false, 31),
("Mishele Grey", false, 39),
("Black Stonemight", false, 37);

